### ISSUE TITLE
Errors in parsing long utf-8 content-disposition headers

### ISSUE THREAD

**Issue by vGimly** [houseabsolute/Courriel#10]
There are two errors when parsing email headers like Content-Disposition with name / filename attribute.
Added two test cases and a solution for them.

1. For the case when there is no space before the beginning of the MIME construction =? UTF-8 ?? ?=. This results in a non-decoded beginning part of the attribute value.
The Courriel::Headers::_mime_decode function uses the too hungry $mime_word regexp: <unencoded>\S+ can be replaced with \S+**?** to fix this issue. Probably this needs more testing (but current tests are passed).
 
2. There can be double-utf-8 encoded (damaged) parts of attribute ($part->disposition->filename).
In the Courriel::Helpers::_parse_attributes function in the call of _decode_raw_value for the logical path $order>0, the charset attribute of the first (0) element should be used as an charset argument:
$attrs->{$name}[0]{charset}, not $attrs->{$name}[$order]{charset}, because the only first element ($order=0) have defined charset attribute, not current.

There should be a better solution, with concatenating all the attributes with same name together without any decoding at the beginning, decoding the percent encoding and only then using Encode :: decode to get the result, since decoding multibyte characters, split between attributes in the middle can be unpredictable (erroneously).

**Comment by autarch** [comment]
Thanks for the report. A PR would be welcome. Even if you can't come up with a fix, a PR with just some failing tests would be hugely helpful!

**Comment by vGimly** [comment]
Not very experienced in github :) Added pull request with test cases and fixes.

**Comment by autarch** [comment]
This is fixed in the latest release, v0.49.
